import { StyleSheet } from "react-native";
import { colors, spacing } from "./theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, // fond général doux
  container: { flex: 1, padding: 0, backgroundColor: colors.background },
  header: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.background,
    marginBottom: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    zIndex: 2,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.text,
    marginBottom: spacing.md,
    letterSpacing: 0.5,
  },
  tabs: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
    gap: 8,
    backgroundColor: "transparent",
    borderRadius: 16,
    padding: 2,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderBottomWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 14,
    marginHorizontal: 2,
    transitionProperty: "backgroundColor",
    transitionDuration: "200ms",
  },
  tabActive: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  tabText: {
    color: colors.mutedText,
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  tabTextActive: {
    color: "#fff",
    fontWeight: "800",
  },
  addBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 28,
    marginBottom: 10,
    elevation: 2,
    shadowColor: colors.primary,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    // minWidth: 140,
  },
  addBtnText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  filters: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.background,
    flexDirection: "column",
    gap: 6,
  },
  input: {
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: spacing.md,
    marginBottom: spacing.sm,
    color: colors.text,
    borderWidth: 1.5,
    borderColor: colors.border,
    fontSize: 15,
  },
  chip: {
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: colors.background,
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginBottom: 4,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  chipText: {
    color: colors.text,
    fontWeight: "600",
    fontSize: 14,
  },
  chipTextActive: {
    color: "#fff",
    fontWeight: "700",
  },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  empty: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.lg,
  },
  emptyText: { color: colors.mutedText, fontSize: 17, fontWeight: "600" },
  card: {
    backgroundColor: colors.primaryDark,
    borderRadius: 16,
    marginVertical: 10,
    marginHorizontal: spacing.lg,
    flexDirection: "row",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardImage: {
    width: 150,
    height: "100%",
    objectFit: "cover",
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  noImage: {
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
  },
  noImageText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  cardContent: { flex: 1, padding: spacing.md, justifyContent: "center" },
  cardTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.surface,
    marginBottom: 2,
  },
  cardCategory: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "700",
    marginBottom: 2,
  },
  cardDesc: { fontSize: 14, color: colors.primary, marginBottom: 2 },
  cardLocation: { fontSize: 13, color: colors.mutedText },
  cardDate: { fontSize: 12, color: colors.mutedText, marginTop: 2 },
  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: spacing.md,
    gap: 4,
  },
  pageDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.primary,
    marginHorizontal: 4,
  },
  pageDotActive: { backgroundColor: colors.primary },
  modalSafe: { flex: 1, backgroundColor: colors.background },
  modalContent: { padding: spacing.lg },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
    marginBottom: spacing.md,
    letterSpacing: 0.2,
  },
  modalImage: {
    width: "100%",
    height: 220,
    borderRadius: 10,
    backgroundColor: colors.background,
    marginBottom: spacing.md,
  },
  modalImageCarousel: {
    width: 220,
    height: 180,
    borderRadius: 10,
    backgroundColor: colors.background,
    marginRight: 14,
  },
  modalDesc: { fontSize: 16, color: colors.text, marginBottom: spacing.md },
  modalLabel: { fontWeight: "700", color: colors.text, marginTop: 8 },
  modalValue: { fontWeight: "400", color: colors.text },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: spacing.lg,
    gap: 14,
  },
  deleteBtn: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 22,
    marginRight: 8,
    elevation: 1,
  },
  deleteBtnText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  closeBtn: {
    backgroundColor: colors.background,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  closeBtnText: { color: colors.primary, fontWeight: "800", fontSize: 15 },
  editBtn: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 22,
    marginRight: 8,
    elevation: 1,
  },
  editBtnText: { color: "#fff", fontWeight: "800", fontSize: 15 },
});
